from enum import Enum


class Accident(Enum):
    CRASH_DATE = 'CRASH DATE',
    CRASH_TIME = 'CRASH TIME',
    BOROUGH = 'BOROUGH',
    ZIP_CODE = 'ZIP CODE',
    LATITUDE = 'LATITUDE',
    LONGITUDE = 'LONGITUDE',
    LOCATION = 'LOCATION',
    ON_STREET_NAME = 'ON STREET NAME',
    CROSS_STREET_NAME = 'CROSS STREET NAME',
    OFF_STREET_NAME = 'OFF STREET NAME',
    NUMBER_OF_PERSONS_INJURED = 'NUMBER OF PERSONS INJURED',
    NUMBER_OF_PERSONS_KILLED = 'NUMBER OF PERSONS KILLED',
    NUMBER_OF_PEDESTRIANS_INJURED = 'NUMBER OF PEDESTRIANS INJURED',
    NUMBER_OF_PEDESTRIANS_KILLED = 'NUMBER OF PEDESTRIANS KILLED',
    NUMBER_OF_CYCLIST_INJURED = 'NUMBER OF CYCLIST INJURED',
    NUMBER_OF_CYCLIST_KILLED = 'NUMBER OF CYCLIST KILLED',
    NUMBER_OF_MOTORIST_INJURED = 'NUMBER OF MOTORIST INJURED',
    NUMBER_OF_MOTORIST_KILLED = 'NUMBER OF MOTORIST KILLED',
    CONTRIBUTING_FACTOR_VEHICLE_1 = 'CONTRIBUTING FACTOR VEHICLE 1',
    CONTRIBUTING_FACTOR_VEHICLE_2 = 'CONTRIBUTING FACTOR VEHICLE 2',
    CONTRIBUTING_FACTOR_VEHICLE_3 = 'CONTRIBUTING FACTOR VEHICLE 3',
    CONTRIBUTING_FACTOR_VEHICLE_4 = 'CONTRIBUTING FACTOR VEHICLE 4',
    CONTRIBUTING_FACTOR_VEHICLE_5 = 'CONTRIBUTING FACTOR VEHICLE 5',
    COLLISION_ID = 'COLLISION_ID',
    VEHICLE_TYPE_CODE_1 = 'VEHICLE TYPE CODE 1',
    VEHICLE_TYPE_CODE_2 = 'VEHICLE TYPE CODE 2',
    VEHICLE_TYPE_CODE_3 = 'VEHICLE TYPE CODE 3',
    VEHICLE_TYPE_CODE_4 = 'VEHICLE TYPE CODE 4',
    VEHICLE_TYPE_CODE_5 = 'VEHICLE TYPE CODE 5'

